apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 20001
      targetPort: 20001
      protocol: TCP
  selector:
    app: kiali
