apiVersion: v2
appVersion: 2.0.3
description: Chaos Mesh® is a cloud-native Chaos Engineering platform that orchestrates
  chaos on Kubernetes environments.
home: https://chaos-mesh.org
icon: https://raw.githubusercontent.com/pingcap/chaos-mesh/master/static/logo.svg
keywords:
- chaos-engineering
- resiliency
- fault-injection
- kubernetes
- testing
name: chaos-mesh
sources:
- https://github.com/pingcap/chaos-mesh
version: 2.0.3
