apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "chaos-daemon.svc" . }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: chaos-daemon
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: {{ .Values.chaosDaemon.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: http
      port: {{ .Values.chaosDaemon.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "chaos-mesh.selectors" . | nindent 4 }}
    app.kubernetes.io/component: chaos-daemon
