apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: metrics-app
  namespace: default
spec:
  hosts:
    - metrics.ramil.local
  gateways:
    - monitoring/monitoring-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: metrics-app.default.svc.cluster.local
            port:
              number: 8080

