replicaCount: 1

image:
  repository: metrics-test
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

affinityRules:
  enableHardAntiAffinity: true
  separateFrom:
    - key: app.kubernetes.io/name
      value: metrics-test
      weight: 100

virtualService:
  enabled: true
  name: metrics-app
  namespace: default
  gateway: 
    - monitoring/monitoring-gateway
  hosts:
    - metrics.ramil.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: metrics-test.default.svc.cluster.local
            port:
              number: 8080

