replicaCount: 1

image:
  repository: metrics-test
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nginx:
  config: |
    server {
      listen 80;
      location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
      location /stub_status {
        stub_status;
      }
    }

affinityRules:
  enableHardAntiAffinity: true
  separateFrom:
    - key: app.kubernetes.io/app
      value: metrics-test
      weight: 100

virtualService:
  enabled: true
  name: metrics-app
  namespace: default
  gateway: 
    - monitoring/monitoring-gateway
  hosts:
    - metrics.ramil.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: metrics-test.default.svc.cluster.local
            port:
              number: 8080

