apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: global-network-delay-11
  annotations:
    chaos-mesh.org/webhook-ignore: "true"
spec:
  action: delay
  mode: all  # Targets all matching pods
  selector:
    namespaces: 
      - 'default'
      - 'istio-system'
    expressionSelectors:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
    labelSelectors: {}
  delay:
    latency: "100ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"


