apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: cluster-wide-network-latency
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - ".*"
    expressionSelectors:
      - namespace!~"kube-system"
  delay:
    latency: "100ms"
    correlation: "25"
    jitter: "50ms"
  duration: "5m"
  scheduler:
    cron: "@hourly"

