# templates/virtualservice.yaml
{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  gateways:
    - {{ .Values.virtualService.gateway }}
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  http:
    {{- toYaml .Values.virtualService.http | nindent 4 }}
{{- end }}
